#!/bin/sh -eu

TELNET_PORT=23
NCAT_COPY_PORT=12345
CONNECT_TIMEOUT=5

if [ $# -ne 3 ]; then
    echo "USAGE: ${0} <source IP> <source filename> <destination filename>"
    exit 1
fi

src_ip="${1}"
src_fname="${2}"
dst_fname="${3}"

(
    set -eu
    trap "echo; echo exit" EXIT

    printf "set -eu\n"

    printf "busybox nc -w 4 -l -p %s <\"%s\"\n" "${NCAT_COPY_PORT}" "${src_fname}"
    start_time=$( date "+%s" )
    while true; do
        ncat --wait 1 --no-shutdown \
            "${src_ip}" "${NCAT_COPY_PORT}" \
            >"${dst_fname}" 2>/dev/null </dev/null && break
        cur_time=$( date "+%s" )
        if [ $(( $cur_time - $start_time )) -gt $CONNECT_TIMEOUT ]; then
            echo "ERROR: Unable to connect via ncat" >&2
            exit 1
        fi
    done
) | ncat --wait 4 --no-shutdown "${src_ip}" "${TELNET_PORT}"
